id: A2DE30D23
title: Maṇḍala Offering from Longsal Dorje Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:44.328170
  last_modified_at: 2022-03-01 00:42:44.328175
