id: A2DE30D23
title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:44.334095
  last_modified_at: 2022-03-01 00:42:44.334102
